Repository InvisiblePro/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#1 Factorial of a Number using While Loop
  python/factorial_using_loop.py
Labels: hacktoberfest-accepted

#2 Create Tip Calculator.py
  python/Tip Calculator.py
Labels: good first issue, hacktoberfest-accepted, excellence

#3 There is bit update in programs...
  java/P24.java
Labels: good first issue, hacktoberfest-accepted, excellence

#7 added a java plaindrome file
  java/PalindromeExample.java
Labels: hacktoberfest-accepted, excellence

#6 Create BMI Calculator.py
  python/BMI Calculator.py
Labels: hacktoberfest-accepted, excellence

#5 Pattern Printing Problem in C++
  C++/Pattern Printing Problems/PyramidPattern_asterisk.cpp
  README.md
Labels: hacktoberfest-accepted, excellence

#8 I added a number guessing game in python
  python/number guesser.py
Labels: hacktoberfest-accepted, excellence

#9 Added a C++ quicksort implementation.
  .vscode/settings.json
  C++/sorting/quicksort.cpp
Labels: hacktoberfest-accepted, excellence

#10 Create Stone_Paper_Scissor_Game.py
  python/Stone_Paper_Scissor_Game.py
Labels: good first issue, hacktoberfest-accepted, excellence

#11 GuessTheNumber
  java/GuessTheNumber.java
Labels: hacktoberfest-accepted, excellence

#13 Create factorial.java
  java/factorial.java
Labels: good first issue, hacktoberfest-accepted, excellence

#14 email validation java
  java/emailvalidation.java
Labels: good first issue, hacktoberfest-accepted, excellence

#15 Created oddeven checker using java
  java/oddevenchecker.java
Labels: good first issue, hacktoberfest-accepted, excellence

#16 Created oddevenchecker.py
  python/oddevenchecker.py
Labels: good first issue, hacktoberfest-accepted, excellence

#29 Create PalindromeChecker.py
  python/PalindromeChecker.py
Labels: Good first issue, hacktoberfest-accepted, Hacktoberfest-2022

#76 Count maximum number of points on same line
  C++/maximum_points_on_same_line.cpp
Labels: hacktoberfest-accepted, Hacktoberfest-2022
